#define FALSE 0
#define TRUE 1

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600
#define ASPECT_RATIO SCREEN_HEIGHT/SCREEN_WIDTH
#define SCREEN_CENTER Vector2(SCREEN_WIDTH >> 1, SCREEN_HEIGHT >> 1)

#define FPS 60
#define FRAME_TARGET_TIME (1000/FPS)

#define PI 3.1415