#define FALSE 0
#define TRUE 1

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600
#define SCREEN_CENTER Vector2(WINDOW_WIDTH >> 1, WINDOW_HEIGHT >> 1)

#define FPS 60
#define FRAME_TARGET_TIME (1000/FPS)

#define PI 3.1415